@startuml OCI_Container_Service

!define SPRITESURL https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/v1.1/sprites
!includeurl SPRITESURL/github.puml
!includeurl SPRITESURL/terraform.puml
!includeurl SPRITESURL/quarkus.puml
!includeurl SPRITESURL/oracle.puml

' Repository / CI
rectangle "<$github>\ntuxtor/devsecops-oci" as repo{
    file "<$terraform>"
    file "<$oracle,color=#C74634>"
}

rectangle "OCI" as cloud {
  rectangle "OCI DNS\ntf.vorozco.com (zone)" as oci_dns

  rectangle "Region: us-ashburn-1\nCompartment: Terraform" as region {
    rectangle "Docker Hub\nhelidon-cloudnative-workload" as ocir

    rectangle "VCN: vorozco-vcn" as vcn {

      rectangle "Public Subnets (3 ADs)\n- Container Instances" as private_subnets {
        rectangle "OCI Compute\n(Raw instance / Simple container service / serverless containers)" as containers {
            ' Ingress/proxy and application containers modeled as container instances
            rectangle "helidon-group\nhelidon app " as helidon_group
        }
      }
    }
  }
}

' Relationships and traffic flows
repo --> cloud : GitHub Actions (CI/CD)
ocir -> containers : image pulls (Docker Hub -> Compute)
oci_dns ...> containers : helidon-ci.tf.vorozco.com


@enduml