name: full-deployment.yml
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      infra_bootstrap:
        description: 'Bootstrap infrastructure'
        required: true
        default: 'false'

permissions:
  contents: read

jobs:
  quarkus:
    name: 'Quarkus'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Run Maven tests
        run: ./mvnw verify spotbugs:check
        working-directory: quarkus-cloud-native-workload
      - name: Docker build
        run: ./mvnw k8s:build
        working-directory: quarkus-cloud-native-workload
      - name: Run Trivy security scan (Docker)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: "image"
          image-ref: docker.io/tuxtor/quarkus-cloud-native-workload:latest
          format: "table"
          exit-code: "0"
          severity: 'CRITICAL,HIGH'
      - name: Docker push
        if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        run: ./mvnw -Djkube.docker.username=tuxtor -Djkube.docker.password=${{ secrets.DOCKER_PAT }} k8s:push
        working-directory: quarkus-cloud-native-workload
  terraform:
    needs: quarkus
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      TF_VAR_api_fingerprint: ${{ secrets.OCI_API_FINGERPRINT }}
      TF_VAR_api_private_key_path: "$HOME/oci_api_key.pem"
      TF_VAR_api_private_key_passphrase: ${{ secrets.OCI_API_KEY_PASSPHRASE }}
      TF_VAR_tenancy_id: ${{ secrets.OCI_TENANCY_ID }}
      TF_VAR_user_id: ${{ secrets.OCI_USER_ID }}
      TF_VAR_region: ${{ secrets.OCI_REGION }}
      TF_VAR_compartment_ocid: ${{ secrets.OCI_COMPARTMENT_OCID }}
      TF_VAR_oci_state_bucket: ${{ secrets.OCI_STATE_BUCKET }}
      TF_VAR_oci_state_bucket_namespace: ${{ secrets.OCI_STATE_BUCKET_NAMESPACE }}
      TF_VAR_aws_state_bucket: ${{ secrets.TF_VAR_AWS_STATE_BUCKET }}
      TF_VAR_infra_bootstrap: ${{ github.event.inputs.infra_bootstrap || 'false' }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Prepare API Key for OCI
        run: |
          mkdir -p ~/.oci
          echo "${{ secrets.OCI_API_PRIVATE_KEY }}" > $HOME/.oci/oci_api_key.pem
          chmod 600 $HOME/.oci/oci_api_key.pem
      - name: Create OCI config directory and file
        run: |
          echo "[DEFAULT]" > ~/.oci/config
          echo "user=${{ secrets.OCI_USER_ID }}" >> ~/.oci/config
          echo "fingerprint=${{ secrets.OCI_API_FINGERPRINT }}" >> ~/.oci/config
          echo "key_file=~/.oci/oci_api_key.pem" >> ~/.oci/config
          echo "tenancy=${{ secrets.OCI_TENANCY_ID }}" >> ~/.oci/config
          echo "region=${{ secrets.OCI_REGION }}" >> ~/.oci/config
          echo "pass_phrase=${{ secrets.OCI_API_KEY_PASSPHRASE }}" >> ~/.oci/config
      - name: Run Trivy security scan (IaC)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: "fs"
          scan-ref: oci-infra
          format: "table"
          exit-code: "0"
          severity: 'CRITICAL,HIGH'
          scanners: 'misconfig,secret'
          cache: 'false'
      - name: Terraform Init
        run: terraform init
        working-directory: oci-infra
      - name: Terraform Plan
        run: terraform plan -input=false
        working-directory: oci-infra
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        run: terraform apply -auto-approve
        working-directory: oci-infra